version: '3.7'
services:
  db:
    image: postgres:15.2-alpine
    container_name: stockingapp-postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=stockingapp
    ports:
      - '5432:5432'
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      # - ./data:/var/lib/postgresql/data
      - ./sql:/raw/data
